<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jurnal extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Jurnal_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template', 'jurnal/jurnal_list');
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Jurnal_model->json();
    }

    public function read($id)
    {
        $row = $this->Jurnal_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id_jurnal' => $row->id_jurnal,
                'id_presensi' => $row->id_presensi,
                'isi' => $row->isi,
            );
            $this->template->load('template', 'jurnal/jurnal_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jurnal'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jurnal/create_action'),
            'id_jurnal' => set_value('id_jurnal'),
            'id_presensi' => set_value('id_presensi'),
            'isi' => set_value('isi'),
        );
        $this->template->load('template', 'jurnal/jurnal_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'id_presensi' => $this->input->post('id_presensi', TRUE),
                'isi' => $this->input->post('isi', TRUE),
            );

            $this->Jurnal_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('jurnal'));
        }
    }

    public function update($id)
    {
        $row = $this->Jurnal_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jurnal/update_action'),
                'id_jurnal' => set_value('id_jurnal', $row->id_jurnal),
                'id_presensi' => set_value('id_presensi', $row->id_presensi),
                'isi' => set_value('isi', $row->isi),
            );
            $this->template->load('template', 'jurnal/jurnal_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jurnal'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_jurnal', TRUE));
        } else {
            $data = array(
                'id_presensi' => $this->input->post('id_presensi', TRUE),
                'isi' => $this->input->post('isi', TRUE),
            );

            $this->Jurnal_model->update($this->input->post('id_jurnal', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jurnal'));
        }
    }

    public function delete($id)
    {
        $row = $this->Jurnal_model->get_by_id($id);

        if ($row) {
            $this->Jurnal_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jurnal'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jurnal'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('id_presensi', 'id presensi', 'trim|required');
        $this->form_validation->set_rules('isi', 'isi', 'trim|required');

        $this->form_validation->set_rules('id_jurnal', 'id_jurnal', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Jurnal.php */
/* Location: ./application/controllers/Jurnal.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-19 03:11:31 */
/* http://harviacode.com */