<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Presensi_hrd extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Presensi_hrd_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template', 'presensi_hrd/presensi_list');
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Presensi_hrd_model->json();
    }

    public function read($id)
    {
        $row = $this->Presensi_hrd_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id_presensi' => $row->id_presensi,
                'id_karyawan' => $row->id_karyawan,
                'tanggal' => $row->tanggal,
                'waktu_masuk' => $row->waktu_masuk,
                'waktu_keluar' => $row->waktu_keluar,
            );
            $this->template->load('template', 'presensi_hrd/presensi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('presensi_hrd'));
        }
    }

    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "presensi.xls";
        $judul = "presensi";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");
        xlsWriteLabel($tablehead, $kolomhead++, "Id Karyawan");
        xlsWriteLabel($tablehead, $kolomhead++, "Nama");
        xlsWriteLabel($tablehead, $kolomhead++, "Tanggal");
        xlsWriteLabel($tablehead, $kolomhead++, "Waktu Masuk");
        xlsWriteLabel($tablehead, $kolomhead++, "Waktu Keluar");

        foreach ($this->Presensi_hrd_model->get_all() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
            xlsWriteNumber($tablebody, $kolombody++, $nourut);
            xlsWriteNumber($tablebody, $kolombody++, $data->id_karyawan);
            xlsWriteNumber($tablebody, $kolombody++, $data->nama);
            xlsWriteLabel($tablebody, $kolombody++, $data->tanggal);
            xlsWriteLabel($tablebody, $kolombody++, $data->waktu_masuk);
            xlsWriteLabel($tablebody, $kolombody++, $data->waktu_keluar);

            $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }
}

/* End of file Presensi_hrd.php */
/* Location: ./application/controllers/Presensi_hrd.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-18 15:56:36 */
/* http://harviacode.com */