<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Cuti_hrd_model extends CI_Model
{

    public $table = 'cuti';
    public $id = 'id_cuti';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('cuti.id_cuti,cuti.id_karyawan,karyawan.nama,cuti.tanggal1,cuti.tanggal2,cuti_jenis.jenis,cuti.id_jenis,cuti.validasi');
        // $this->datatables->where('cuti.id_karyawan', 'karyawan.id_karyawan', FALSE);
        // $this->datatables->where('cuti.id_karyawan', $_SESSION['id_users']);
        // $this->datatables->where('cuti.id_jenis', 'cuti_jenis.id_jenis', FALSE);
        // // $this->datatables->select('id_cuti,id_karyawan,tanggal1,tanggal2,id_jenis,status,validasi');
        $this->datatables->from('cuti');
        $this->datatables->join('karyawan', 'cuti.id_karyawan = karyawan.id_karyawan');
        $this->datatables->join('cuti_jenis', 'cuti.id_jenis = cuti_jenis.id_jenis');
        //add this line for join
        //$this->datatables->join('table2', 'cuti.field = table2.field');
        // $this->datatables->where('cuti.id_karyawan', $_SESSION['id_users']);
        $this->datatables->add_column('valid', 
                                        anchor(site_url('cuti_hrd/accept/$1'),'<i class="fa fa-check" aria-hidden="true"></i>', 'class="btn btn-success btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"') . "
                                    " . anchor(site_url('cuti_hrd/reject/$1'),'<i class="fa fa-times" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_cuti');
        $this->datatables->add_column('action', anchor(site_url('cuti_hrd/read/$1'), '<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm')) . " 
            " . anchor(site_url('cuti_hrd/update/$1'), '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-primary btn-sm')) . " 
                " . anchor(site_url('cuti_hrd/delete/$1'), '<i class="fa fa-trash-o" aria-hidden="true"></i>', 'class="btn btn-warning btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_cuti');
        return $this->datatables->generate();
    }

    // get all
    function get_all($id)
    {
        $this->db->where($this->id, $id);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->datatables->select('cuti.id_cuti,cuti.id_karyawan,karyawan.nama,cuti.tanggal1,cuti.tanggal2,cuti_jenis.jenis,cuti.id_jenis,cuti.validasi');
        $this->datatables->from('cuti');
        $this->datatables->join('karyawan', 'cuti.id_karyawan = karyawan.id_karyawan');
        $this->datatables->join('cuti_jenis', 'cuti.id_jenis = cuti_jenis.id_jenis');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('cuti.id_karyawan', $q);
        $this->db->or_like('cuti.id_cuti', $q);
        $this->db->or_like('karyawan.nama', $q);
        $this->db->or_like('cuti.tanggal1', $q);
        $this->db->or_like('cuti.tanggal2', $q);
        $this->db->or_like('cuti_jenis.jenis', $q);
        $this->db->or_like('cuti.validasi', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

     // get data with limit and search
     function get_limit_data($limit, $start = 0, $q = NULL)
     {
         $this->db->order_by($this->id, $this->order);
         $this->db->like('cuti.id_karyawan', $q);
         $this->db->or_like('cuti.id_cuti', $q);
         $this->db->or_like('karyawan.nama', $q);
         $this->db->or_like('cuti.tanggal1', $q);
         $this->db->or_like('cuti.tanggal2', $q);
         $this->db->or_like('cuti_jenis.jenis', $q);
         $this->db->or_like('cuti.validasi', $q);
         $this->db->limit($limit, $start);
         return $this->db->get($this->table)->result();
     }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Cuti_hrd_model.php */
/* Location: ./application/models/Cuti_hrd_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-18 15:16:46 */
/* http://harviacode.com */