<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Presensi_hrd_model extends CI_Model
{

    public $table = 'presensi';
    public $id = 'id_presensi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id_presensi, presensi.id_karyawan,tanggal,waktu_masuk,waktu_keluar, nama');
        $this->datatables->from('presensi');
        //add this line for join
        //$this->datatables->join('table2', 'presensi.field = table2.field');
        $this->datatables->join('karyawan', 'presensi.id_karyawan = karyawan.id_karyawan');
        // $this->datatables->order_by('tanggal DESC');
        $this->datatables->add_column('action', anchor(site_url('presensi_hrd/read/$1'), '<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . " 
            " . anchor(site_url('presensi_hrd/update/$1'), '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . " 
                " . anchor(site_url('presensi_hrd/delete/$1'), '<i class="fa fa-trash-o" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_presensi');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_presensi', $q);
        $this->db->or_like('id_karyawan', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('waktu_masuk', $q);
        $this->db->or_like('waktu_keluar', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_presensi', $q);
        $this->db->or_like('id_karyawan', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('waktu_masuk', $q);
        $this->db->or_like('waktu_keluar', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }


}

/* End of file Presensi_hrd_model.php */
/* Location: ./application/models/Presensi_hrd_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-18 15:56:36 */
/* http://harviacode.com */