<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Presensi_model extends CI_Model
{

    public $table = 'presensi';
    public $id = 'id_presensi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id_presensi,id_karyawan,tanggal,waktu_masuk,waktu_keluar');
        $this->datatables->from('presensi');
        //add this line for join
        //$this->datatables->join('table2', 'presensi.field = table2.field');
        $this->datatables->where(array('id_karyawan' => $_SESSION['id_users']));
        $this->datatables->add_column('action', anchor(site_url('presensi/read/$1'), '<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . " 
            " . anchor(site_url('/jurnal/$1'), '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-primary btn-sm')) . " 
                ", 'id_presensi');
        return $this->datatables->generate();
    }

    function jurnal()
    {
        $data['id_presensi'] = $this->db->get_where('presensi', array('id_presensi' =>  $this->uri->segment(3)))->row_array();
        $data['isi'] = $this->db->select('isi')->get('jurnal')->result();
        $this->template->load('template', 'jurnal/jurnal_list', $data);
    }

    // get all
    // function get_all()
    // {
    //     $this->db->where(array('id_karyawan' => $_SESSION['id_users']));
    //     $this->db->order_by($this->id, $this->order);
    //     return $this->db->get($this->table)->result();
    // }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_presensi', $q);
        $this->db->or_like('id_karyawan', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('waktu_masuk', $q);
        $this->db->or_like('waktu_keluar', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_presensi', $q);
        $this->db->or_like('id_karyawan', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('waktu_masuk', $q);
        $this->db->or_like('waktu_keluar', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Presensi_model.php */
/* Location: ./application/models/Presensi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-16 08:36:54 */
/* http://harviacode.com */